import '../llm/entity_resolution/phonetic_matching_helper.dart';
import '../llm/entity_resolution/transliteration_helper.dart';

/// Represents a recovered domain anchor token/phrase.
class DomainAnchorRecovery {
  final String originalPhrase;
  final String canonicalPhrase;
  final String category; // 'country' or 'action'
  final String matchedEntry;
  final String language;
  final double confidence;
  final String strategy;

  const DomainAnchorRecovery({
    required this.originalPhrase,
    required this.canonicalPhrase,
    required this.category,
    required this.matchedEntry,
    required this.language,
    required this.confidence,
    required this.strategy,
  });

  Map<String, dynamic> toJson() => {
    'originalPhrase': originalPhrase,
    'canonicalPhrase': canonicalPhrase,
    'category': category,
    'matchedEntry': matchedEntry,
    'language': language,
    'confidence': confidence,
    'strategy': strategy,
  };
}

/// Legitimate finite closed-set application vocabulary for rally countries and action concepts.
///
/// Contains ONLY legitimate translations/synonyms across the 19 supported languages.
/// MUST NOT contain any open-set entities (drivers, rallies, stages, uploaders).
class MultilingualDomainLexicon {
  const MultilingualDomainLexicon._();

  /// Canonical rally database countries mapped to localized names/translations across 19 languages.
  static const Map<String, Map<String, List<String>>> countries = {
    'Ireland': {
      'en': ['ireland', 'republic of ireland'],
      'ga': ['éirinn', 'eirinn', 'éire', 'eire', 'in éirinn', 'd\'éirinn'],
      'cy': ['iwerddon', 'yn iwerddon', 'werddon'],
      'de': ['irland'],
      'fr': ['irlande'],
      'es': ['irlanda'],
      'it': ['irlanda'],
      'pt': ['irlanda'],
      'nl': ['ierland'],
      'pl': ['irlandia', 'irlandii', 'w irlandii'],
      'nb': ['irland', 'i irland'],
      'lv': ['īrija', 'irija', 'īrijā', 'irija'],
      'lt': ['airija', 'airijoje'],
      'cs': ['irsko', 'irsku', 'v irsku'],
      'hr': ['irska', 'irskoj', 'u irskoj'],
      'sk': ['írsko', 'irsko', 'írsku', 'irsku', 'v írsku'],
      'ur': ['آئرلینڈ', 'ائرلینڈ'],
      'ar': ['أيرلندا', 'ايرلندا', 'إيرلندا'],
      'sw': ['ayalandi', 'ayaland'],
    },
    'United Kingdom': {
      'en': ['united kingdom', 'uk', 'great britain', 'britain', 'england', 'scotland', 'wales', 'northern ireland'],
      'cy': ['y deyrnas unedig', 'prydain fawr', 'lloegr', 'cymru', 'yr alban'],
      'ga': ['an ríocht aontaithe', 'an bhreatain mhór'],
      'de': ['vereinigtes königreich', 'grossbritannien', 'england', 'schottland', 'wales'],
      'fr': ['royaume-uni', 'grande-bretagne', 'angleterre', 'écosse'],
      'es': ['reino unido', 'gran bretaña', 'inglaterra', 'escocia', 'gales'],
      'it': ['regno unito', 'gran bretagna', 'inghilterra', 'scozia', 'galles'],
      'pt': ['reino unido', 'grã-bretanha', 'inglaterra', 'escócia'],
      'nl': ['verenigd koninkrijk', 'groot-brittannië', 'engeland'],
      'pl': ['wielka brytania', 'anglia', 'szkocja', 'walia'],
      'nb': ['storbritannia', 'england', 'skottland'],
      'lv': ['apvienotā karaliste', 'lielbritānija'],
      'lt': ['jungtinė karalystė', 'didžioji britanija'],
      'cs': ['velká británie', 'spojené království', 'anglie'],
      'hr': ['ujedinjeno kraljevstvo', 'velika britanija', 'engleska'],
      'sk': ['veľká británia', 'spojené kráľovstvo', 'anglicko'],
      'ur': ['برطانیہ', 'یونائیٹڈ کنگڈم'],
      'ar': ['المملكة المتحدة', 'بريطانيا'],
      'sw': ['uingereza'],
    },
    'Portugal': {
      'en': ['portugal'],
      'pt': ['portugal', 'em portugal'],
      'es': ['portugal'],
      'fr': ['portugal'],
      'de': ['portugal'],
      'it': ['portogallo'],
      'nl': ['portugal'],
      'pl': ['portugalia', 'w portugalii'],
      'nb': ['portugal'],
      'lv': ['portugāle', 'portugālē'],
      'lt': ['portugalija', 'portugalijoje'],
      'cs': ['portugalsko', 'v portugalsku'],
      'hr': ['portugal', 'u portugalu'],
      'sk': ['portugalsko', 'v portugalsku'],
      'ur': ['پرتگال'],
      'ar': ['البرتغال'],
      'sw': ['ubreno'],
    },
    'France': {
      'en': ['france'],
      'fr': ['france', 'en france'],
      'es': ['francia'],
      'it': ['francia'],
      'de': ['frankreich'],
      'pt': ['frança'],
      'nl': ['frankrijk'],
      'pl': ['francja', 'we francji'],
      'nb': ['frankrike'],
      'lv': ['francija', 'francijā'],
      'lt': ['prancūzija', 'prancūzijoje'],
      'cs': ['francie', 've francii'],
      'hr': ['francuska', 'u francuskoj'],
      'sk': ['francúzsko', 'vo francúzsku'],
      'ur': ['فرانس'],
      'ar': ['فرنسا'],
      'sw': ['ufaransa'],
    },
    'Austria': {
      'en': ['austria'],
      'de': ['österreich', 'in österreich'],
      'fr': ['autriche'],
      'es': ['austria'],
      'it': ['austria'],
      'pt': ['áustria'],
      'nl': ['oostenrijk'],
      'pl': ['austria', 'w austrii'],
      'nb': ['østerrike'],
      'lv': ['austrija', 'austrijā'],
      'lt': ['austrija', 'austrijoje'],
      'cs': ['rakousko', 'v rakousku'],
      'hr': ['austrija', 'u austriji'],
      'sk': ['rakúsko', 'v rakúsku'],
      'ur': ['آسٹریا'],
      'ar': ['النمسا'],
      'sw': ['ostria'],
    },
    'Norway': {
      'en': ['norway'],
      'nb': ['norge', 'i norge'],
      'de': ['norwegen'],
      'fr': ['norvège'],
      'es': ['noruega'],
      'it': ['norvegia'],
      'pt': ['noruega'],
      'nl': ['noorwegen'],
      'pl': ['norwegia', 'w norwegii'],
      'lv': ['norvēģija', 'norvēģijā'],
      'lt': ['norvegija', 'norvegijoje'],
      'cs': ['norsko', 'v norsku'],
      'hr': ['norveška', 'u norveškoj'],
      'sk': ['nórsko', 'v nórsku'],
      'ur': ['ناروے'],
      'ar': ['النرويج'],
      'sw': ['norwe'],
    },
    'Sweden': {
      'en': ['sweden'],
      'de': ['schweden'],
      'fr': ['suède'],
      'es': ['suecia'],
      'it': ['svezia'],
      'pt': ['suécia'],
      'nl': ['zweden'],
      'pl': ['szwecja'],
      'nb': ['sverige'],
      'lv': ['zviedrija'],
      'lt': ['švedija'],
      'cs': ['švédsko'],
      'hr': ['švedska'],
      'sk': ['švédsko'],
      'ur': ['سویڈن'],
      'ar': ['السويد'],
      'sw': ['swidi'],
    },
    'Finland': {
      'en': ['finland'],
      'de': ['finnland'],
      'fr': ['finlande'],
      'es': ['finlandia'],
      'it': ['finlandia'],
      'pt': ['finlândia'],
      'nl': ['finland'],
      'pl': ['finlandia'],
      'nb': ['finland'],
      'lv': ['somija'],
      'lt': ['suomija'],
      'cs': ['finsko'],
      'hr': ['finska'],
      'sk': ['fínsko'],
      'ur': ['فن لینڈ'],
      'ar': ['فنلندا'],
      'sw': ['uinlandi'],
    },
    'Germany': {
      'en': ['germany'],
      'de': ['deutschland', 'in deutschland'],
      'fr': ['allemagne'],
      'es': ['alemania'],
      'it': ['germania'],
      'pt': ['alemanha'],
      'nl': ['duitsland'],
      'pl': ['niemcy', 'w niemczech'],
      'nb': ['tyskland'],
      'lv': ['vācija'],
      'lt': ['vokietija'],
      'cs': ['německo'],
      'hr': ['njemačka'],
      'sk': ['nemecko'],
      'ur': ['جرمنی'],
      'ar': ['ألمانيا'],
      'sw': ['ujerumani'],
    },
    'Italy': {
      'en': ['italy'],
      'it': ['italia', 'in italia'],
      'de': ['italien'],
      'fr': ['italie'],
      'es': ['italia'],
      'pt': ['itália'],
      'nl': ['italië'],
      'pl': ['włochy', 'we włoszech'],
      'nb': ['italia'],
      'lv': ['itālija'],
      'lt': ['italija'],
      'cs': ['itálie'],
      'hr': ['italija'],
      'sk': ['taliansko'],
      'ur': ['اٹلی'],
      'ar': ['إيطاليا'],
      'sw': ['italia'],
    },
    'Spain': {
      'en': ['spain'],
      'es': ['españa', 'en españa'],
      'de': ['spanien'],
      'fr': ['espagne'],
      'it': ['spagna'],
      'pt': ['espanha'],
      'nl': ['spanje'],
      'pl': ['hiszpania', 'w hiszpanii'],
      'nb': ['spania'],
      'lv': ['spānija'],
      'lt': ['ispanija'],
      'cs': ['španělsko'],
      'hr': ['španjolska'],
      'sk': ['španielsko'],
      'ur': ['اسپین', 'ہسپانیہ'],
      'ar': ['إسبانيا'],
      'sw': ['hispania'],
    },
  };

  /// Canonical action concepts mapped to legitimate multilingual translations/synonyms.
  static const Map<String, Map<String, List<String>>> actions = {
    'jump': {
      'en': ['jump', 'jumps', 'jump highlights', 'jump moments', 'jumping', 'big jump'],
      'de': ['sprung', 'sprünge', 'sprung-highlights', 'sprunghighlights', 'sprünge-highlights', 'sprungmomente'],
      'fr': ['saut', 'sauts', 'meilleurs sauts', 'moments de saut'],
      'es': ['salto', 'saltos', 'momentos de saltos', 'mejores saltos', 'destacados de saltos'],
      'it': ['salto', 'salti', 'salti migliori', 'momenti di salto'],
      'pt': ['salto', 'saltos', 'destaques de saltos', 'melhores saltos'],
      'nl': ['sprong', 'sprongen', 'spronghoogtepunten', 'sprong hoogtepunten'],
      'pl': ['skok', 'skoki', 'najciekawsze skoki', 'skoki z udziałem'],
      'nb': ['hopp', 'hopphøydepunkter', 'beste hopp', 'hopp høydepunkter'],
      'lv': ['lēciens', 'lēcieni', 'lēcienas', 'labākie lēcieni', 'labākos lēcienas'],
      'lt': ['šuolis', 'šuoliai', 'šuolius', 'geriausi šuoliai', 'geriausius šuolius'],
      'cs': ['skok', 'skoky', 'nejlepší skoky'],
      'hr': ['skok', 'skokovi', 'skokove', 'najbolji skokovi', 'najbolje skokove'],
      'sk': ['skok', 'skoky', 'najlepšie skoky', 'najlepšie skoky s'],
      'ga': ['léim', 'léimeanna', 'leimeanna', 'buaicphointí léimeanna'],
      'cy': ['naid', 'neidiau', 'uchafbwyntiau neidiau', 'chybwyntiau neidiau'],
      'ur': ['جمپ', 'جمپس', 'چھلانگ', 'جمپس کے ہائی لائٹس', 'ہائی لائٹس'],
      'ar': ['قفزة', 'قفزات', 'لقطات القفزات', 'القفزات المميزة', 'لقطات القفزات المميزة'],
      'sw': ['ruka', 'miruko', 'matukio makuu ya miruko'],
    },
    'drift': {
      'en': ['drift', 'drifts', 'drifting', 'power slide', 'powerslide'],
      'de': ['drift', 'drifts', 'driften'],
      'fr': ['dérive', 'dérapage', 'glissade', 'drifts'],
      'es': ['derrape', 'derrapes', 'drifting', 'derrapando'],
      'it': ['derapata', 'derapate', 'drift'],
      'pt': ['derrapagem', 'derrapagens', 'drift'],
      'nl': ['drift', 'driften', 'slippen'],
      'pl': ['poślizg', 'drifty', 'drift'],
      'nb': ['sladd', 'sladding', 'drift'],
      'lv': ['sānslīde', 'drifts'],
      'lt': ['slydimas', 'driftas'],
      'cs': ['smyk', 'drifty'],
      'hr': ['proklizavanje', 'zanošenje', 'drift'],
      'sk': ['šmyk', 'šmyky', 'drift'],
      'ga': ['sleamhnú', 'drift'],
      'cy': ['llithriad', 'drift'],
      'ur': ['ڈرفٹ'],
      'ar': ['انجراف', 'درفت', 'تفحيط'],
      'sw': ['kuteleza', 'drift'],
    },
    'crash': {
      'en': ['crash', 'crashes', 'accident', 'rollover', 'roll over', 'off road'],
      'de': ['unfall', 'unfälle', 'crash', 'überschlag'],
      'fr': ['crash', 'accident', 'tonneaux', 'sortie de route'],
      'es': ['accidente', 'accidentes', 'choque', 'vuelco', 'salida de pista'],
      'it': ['incidente', 'incidenti', 'schianto', 'cappottamento'],
      'pt': ['acidente', 'acidentes', 'capotamento', 'batida'],
      'nl': ['ongeluk', 'ongeval', 'crash', 'koprol'],
      'pl': ['wypadek', 'wypadki', 'dachowanie', 'kraksa'],
      'nb': ['krasj', 'ulykke', 'rulling'],
      'lv': ['avārija', 'avārijas'],
      'lt': ['avarija', 'avarijos', 'apvirtimas'],
      'cs': ['nehoda', 'havárie', 'převrácení'],
      'hr': ['nesreća', 'sudar', 'izlijetanje', 'prevrtanje'],
      'sk': ['nehoda', 'havária', 'prevrátenie'],
      'ga': ['timpiste', 'tuairt'],
      'cy': ['damwain', 'gwrthdrawiad'],
      'ur': ['حادثہ', 'ٹکر'],
      'ar': ['حادث', 'حوادث', 'انقلاب'],
      'sw': ['ajali'],
    },
    'donut': {
      'en': ['donut', 'donuts', 'doughnut', 'doughnuts', '360 spin'],
      'de': ['donut', 'donuts', 'kreisel'],
      'fr': ['donut', 'donuts', 'tête-à-queue'],
      'es': ['donut', 'donuts', 'trompo'],
      'it': ['donut', 'donuts', 'testacoda'],
      'pt': ['zerinho', 'zerinhos', 'donut'],
      'nl': ['donut', 'donuts'],
      'pl': ['bączek', 'bączki', 'donut'],
      'nb': ['smultring', 'donuts'],
      'lv': ['donut', 'gredzens'],
      'lt': ['spurgos', 'sukimasis'],
      'cs': ['donut', 'hodiny'],
      'hr': ['krafne', 'krafna', 'okretanje'],
      'sk': ['hodiny', 'točenie'],
      'ga': ['fáinne', 'donut'],
      'cy': ['donut'],
      'ur': ['ڈونٹ'],
      'ar': ['دونات', 'دوران'],
      'sw': ['donut'],
    },
    'water_splash': {
      'en': ['water splash', 'watersplash', 'water crossing', 'river crossing'],
      'de': ['wasserdurchfahrt', 'wasserdurchquerung', 'watersplash'],
      'fr': ['gué', 'passage d\'eau', 'splash d\'eau'],
      'es': ['vado', 'paso de agua', 'salpicadura de agua'],
      'it': ['guado', 'passaggio nell\'acqua', 'spruzzo d\'acqua'],
      'pt': ['vau', 'passagem de água'],
      'nl': ['waterdoorwading', 'watersplash'],
      'pl': ['przejazd przez wodę', 'rozbryzg wody'],
      'nb': ['vanngjennomkjøring', 'vannsprut'],
      'lv': ['ūdens šķērsošana'],
      'lt': ['vandens pervaža'],
      'cs': ['brod', 'průjezd vodou'],
      'hr': ['prolazak kroz vodu'],
      'sk': ['brod', 'prejazd vodou'],
      'ga': ['trasnú uisce'],
      'cy': ['croesi dŵr'],
      'ur': ['پانی کا چھینٹا'],
      'ar': ['عبور المياه', 'رش الماء'],
      'sw': ['kuruka maji'],
    },
    'highlights': {
      'en': ['highlights', 'best moments', 'top moments'],
      'de': ['highlights', 'beste momente', 'höhepunkte'],
      'fr': ['meilleurs moments', 'temps forts', 'highlights'],
      'es': ['momentos destacados', 'mejores momentos'],
      'it': ['momenti salienti', 'momenti migliori'],
      'pt': ['momentos destacados', 'melhores momentos', 'destaques'],
      'nl': ['hoogtepunten', 'beste momenten'],
      'pl': ['najciekawsze momenty', 'najlepsze momenty', 'skróty'],
      'nb': ['høydepunkter', 'beste øyeblikk'],
      'lv': ['spilgtākie mirkļi', 'labākie brīži'],
      'lt': ['svarbiausi momentai', 'geriausios akimirkos'],
      'cs': ['nejlepší momenty', 'sestřih'],
      'hr': ['najbolji trenuci', 'naglasci'],
      'sk': ['najlepšie momenty', 'zostrih'],
      'ga': ['buaicphointí', 'buaicphointi'],
      'cy': ['uchafbwyntiau', 'uchafbwynt'],
      'ur': ['ہائی لائٹس', 'اہم لمحات'],
      'ar': ['أبرز اللقطات', 'اللقطات المميزة', 'أفضل اللحظات'],
      'sw': ['matukio makuu', 'vielelezo'],
    },
  };
}
