"""Independent live-DB audit queries. These intentionally do not import production repositories."""
import argparse,asyncio,json
from pathlib import Path
from sqlalchemy import text
from app.db.engine import get_engine

async def fetch(conn,sql,params,key,total_sql=None):
    result=await conn.execute(text(sql),params); ids=[str(x) for x in result.scalars().all()]
    if total_sql:
        total=int((await conn.execute(text(total_sql),params)).scalar_one() or 0)
    else: total=len(ids)
    return ids,total

async def main(fixtures_path,output_path):
    fixtures={x["caseId"]:x for x in json.loads(Path(fixtures_path).read_text())["cases"]}
    audits={
      "participation-basic":("""SELECT DISTINCT ev.event_id FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_driver_profile p ON p.driver_id=el.user_driver_id WHERE LOWER(p.full_name) LIKE :name ORDER BY ev.start_date DESC LIMIT 100""","""SELECT COUNT(DISTINCT ev.event_id) FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_driver_profile p ON p.driver_id=el.user_driver_id WHERE LOWER(p.full_name) LIKE :name""",{"name":"%josh moffett%"}),
      "role-codriver-only-driver":("""SELECT DISTINCT ev.event_id FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_driver_profile p ON p.driver_id=el.user_driver_id WHERE LOWER(p.full_name) LIKE :name ORDER BY ev.start_date DESC LIMIT 100""","""SELECT COUNT(DISTINCT ev.event_id) FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_driver_profile p ON p.driver_id=el.user_driver_id WHERE LOWER(p.full_name) LIKE :name""",{"name":"%max freeman%"}),
      "role-codriver-only-codriver":("""SELECT DISTINCT ev.event_id FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_codriver_profile p ON p.codriver_id=el.user_co_driver_id WHERE LOWER(p.full_name) LIKE :name ORDER BY ev.start_date DESC LIMIT 100""","""SELECT COUNT(DISTINCT ev.event_id) FROM rally_events ev JOIN rally_sub_events se ON se.event_id=ev.event_id JOIN rally_entry_list el ON el.sub_event_id=se.sub_event_id JOIN user_codriver_profile p ON p.codriver_id=el.user_co_driver_id WHERE LOWER(p.full_name) LIKE :name""",{"name":"%max freeman%"}),
      "driver-wins-basic":("""SELECT rr.rally_id FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id JOIN user_driver_profile p ON p.driver_id=(SELECT el.user_driver_id FROM rally_entry_list el WHERE el.id=rr.entry_list_id) WHERE rr.pos_overall=1 AND LOWER(p.full_name) LIKE :name AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED)) ORDER BY (SELECT start_date FROM rally_events WHERE event_id=rr.rally_id) DESC LIMIT 100""","""SELECT COUNT(*) FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id JOIN user_driver_profile p ON p.driver_id=(SELECT el.user_driver_id FROM rally_entry_list el WHERE el.id=rr.entry_list_id) WHERE rr.pos_overall=1 AND LOWER(p.full_name) LIKE :name AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED))""",{"name":"%josh moffett%"}),
      "rally-winner-basic":("""SELECT rr.id FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id WHERE rr.pos_overall=1 AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED)) ORDER BY rr.pos_overall LIMIT 1""",None,{}),
      "finishers-event-range":("""SELECT rr.id FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id WHERE rr.pos_overall IS NOT NULL AND rr.rally_id IN (:a,:b) AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED)) ORDER BY rr.pos_overall LIMIT 10""","""SELECT COUNT(*) FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id WHERE rr.pos_overall IS NOT NULL AND rr.rally_id IN (:a,:b) AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED))""",{"a":"2c411152-5bfe-4292-bd5a-43bc98ba6ab3","b":"00000000-0000-0000-0000-000000000000"}),
      "actions-person-direct":("""SELECT DISTINCT vm.id FROM rally_video_metadata vm JOIN rally_streams stream ON stream.video_id=vm.video_id JOIN rally_entry_list crew ON crew.id=vm.entry_list_id JOIN user_codriver_profile p ON p.codriver_id=crew.user_co_driver_id WHERE LOWER(p.full_name) LIKE :name AND stream.on_demand_url IS NOT NULL AND stream.on_demand_url!='' AND COALESCE(stream.video_type,'')!='instantReplay' ORDER BY vm.id DESC LIMIT 100""","""SELECT COUNT(DISTINCT vm.id) FROM rally_video_metadata vm JOIN rally_streams stream ON stream.video_id=vm.video_id JOIN rally_entry_list crew ON crew.id=vm.entry_list_id JOIN user_codriver_profile p ON p.codriver_id=crew.user_co_driver_id WHERE LOWER(p.full_name) LIKE :name AND stream.on_demand_url IS NOT NULL AND stream.on_demand_url!='' AND COALESCE(stream.video_type,'')!='instantReplay'""",{"name":"%max freeman%"}),
      "videos-person-direct":("""SELECT DISTINCT video.id FROM rally_videos video JOIN rally_video_metadata tagged ON tagged.video_id=video.id JOIN rally_entry_list crew ON crew.id=tagged.entry_list_id JOIN user_codriver_profile p ON p.codriver_id=crew.user_co_driver_id JOIN rally_streams stream ON stream.video_id=video.id WHERE LOWER(p.full_name) LIKE :name AND stream.on_demand_url IS NOT NULL AND stream.on_demand_url!='' AND COALESCE(stream.video_type,'')!='instantReplay' ORDER BY video.id DESC LIMIT 100""","""SELECT COUNT(DISTINCT video.id) FROM rally_videos video JOIN rally_video_metadata tagged ON tagged.video_id=video.id JOIN rally_entry_list crew ON crew.id=tagged.entry_list_id JOIN user_codriver_profile p ON p.codriver_id=crew.user_co_driver_id JOIN rally_streams stream ON stream.video_id=video.id WHERE LOWER(p.full_name) LIKE :name AND stream.on_demand_url IS NOT NULL AND stream.on_demand_url!='' AND COALESCE(stream.video_type,'')!='instantReplay'""",{"name":"%max freeman%"}),
      "uploaders-basic":("""SELECT CAST(video.uploader_user_id AS CHAR) FROM rally_videos video WHERE video.uploader_user_id IS NOT NULL GROUP BY video.uploader_user_id ORDER BY COUNT(*) DESC LIMIT 20""","""SELECT COUNT(DISTINCT video.uploader_user_id) FROM rally_videos video WHERE video.uploader_user_id IS NOT NULL""",{}),
      "top-drivers-basic":("""SELECT COALESCE(CAST(p.driver_id AS CHAR),rr.crew) FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id LEFT JOIN rally_entry_list crew ON crew.id=rr.entry_list_id LEFT JOIN user_driver_profile p ON p.driver_id=crew.user_driver_id WHERE rr.pos_overall=1 AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED)) GROUP BY p.driver_id,COALESCE(p.full_name,rr.crew) ORDER BY COUNT(DISTINCT rr.rally_id) DESC LIMIT 20""","""SELECT COUNT(DISTINCT COALESCE(CAST(p.driver_id AS CHAR),rr.crew)) FROM rally_results rr JOIN rally_stages s ON s.stage_id=rr.stage_id LEFT JOIN rally_entry_list crew ON crew.id=rr.entry_list_id LEFT JOIN user_driver_profile p ON p.driver_id=crew.user_driver_id WHERE rr.pos_overall=1 AND NOT EXISTS (SELECT 1 FROM rally_stages later JOIN rally_results classified ON classified.stage_id=later.stage_id AND classified.rally_id=rr.rally_id WHERE later.event_id=rr.rally_id AND CAST(later.stage_number AS UNSIGNED)>CAST(s.stage_number AS UNSIGNED))""",{})
    }
    with Path(output_path).open("w") as sink:
        async with get_engine().connect() as conn:
            for case_id,(sql,total_sql,params) in audits.items():
                ids,total=await fetch(conn,sql,params,"id",total_sql)
                sink.write(json.dumps({"schemaVersion":"1.0","runtime":"raw_db","caseId":case_id,"searchQuery":fixtures[case_id]["searchQuery"],"orderedCanonicalIds":ids,"total":total})+"\n")

if __name__=="__main__":
    p=argparse.ArgumentParser();p.add_argument("fixtures");p.add_argument("output");a=p.parse_args();asyncio.run(main(a.fixtures,a.output))
