from enum import StrEnum


class SearchIntent(StrEnum):
    SEARCH_RALLIES = "SEARCH_RALLIES"
    SEARCH_DRIVER_RALLIES = "SEARCH_DRIVER_RALLIES"
    SEARCH_DRIVER_WINS = "SEARCH_DRIVER_WINS"
    GET_RALLY_RESULTS = "GET_RALLY_RESULTS"
    GET_RALLY_TOP_FINISHERS = "GET_RALLY_TOP_FINISHERS"
    SEARCH_VIDEO_ACTIONS = "SEARCH_VIDEO_ACTIONS"
    SEARCH_DRIVER_VIDEOS = "SEARCH_DRIVER_VIDEOS"
    GET_TOP_UPLOADERS = "GET_TOP_UPLOADERS"
    GET_TOP_DRIVERS_BY_WINS = "GET_TOP_DRIVERS_BY_WINS"

